---
name: ❓ Question
description: Ask a question about Miaocha
title: "[Q&A] "
labels: ["question"]
assignees: []

body:
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment (Optional)
      description: Provide versions using the table (optional but helpful)
      value: |
        | Info | Details |
        |------|---------|
        | Miaocha Version | 1.2.3 |
        | Operating System | Ubuntu 22.04 / macOS 14 / Windows 11 |
        | Java | 17.0.x |
      render: markdown

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any extra details that might help answer
