server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: log-manage-system
    version: '@project.version@'
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.19.212:3306/log_manage_system?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hina.log.entity
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
  show-actuator: false
  show-login-endpoint: true

# JWT配置
jwt:
  secret: 8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92
  expiration: 3600000  # 1小时
  refresh-expiration: 86400000  # 24小时

# 自定义配置
sql:
  query:
    csv:
      export:
        dir: /tmp/sql-exports

# Logstash配置
logstash:
  # Logstash压缩包路径
  package-path: /opt/logstash/logstash-8.11.1.tar.gz
  # 远程部署目录
  deploy-dir: ~/logstash

    