server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: log-manage-system
    version: '@project.version@'
  profiles:
    active: '@spring.profiles.active@'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:log_manage_system}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/v1,classpath:db/migration/v2
    table: flyway_schema_history

# 环境配置
environment: '@environment@'

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hina.log.entity
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
  show-actuator: false
  show-login-endpoint: true

# JWT配置
jwt:
  secret: 8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92
  expiration: 3600000  # 1小时
  refresh-expiration: 86400000  # 24小时

# 自定义配置
sql:
  query:
    csv:
      export:
        dir: /tmp/sql-exports

# Logstash配置
logstash:
  # Logstash压缩包路径
  package-path: ${LOGSTASH_PACKAGE_PATH}
  # 远程部署目录
  deploy-dir: ${LOGSTASH_DEPLOY_DIR:/opt/logstash}
  # 进程监控配置
  monitor:
    # 监控间隔时间（毫秒），默认10分钟
    interval: 600000

    