server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: miaocha
    version: "@project.version@"
  profiles:
    active: "@spring.profiles.active@"
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:log_manage_system}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/v1,classpath:db/migration/v2
    table: flyway_schema_history

  mail:
    host: ${SMTP_HOST:}
    port: ${SMTP_PORT:25}
    username: ${SMTP_USER:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          ssl:
            enable: ${SMTP_SSL:false}
          auth: ${SMTP_AUTH:false}

  ai:
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
    tools:
      throw-exception-on-error: true

# 环境配置
environment: "@environment@"

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hina.log.entity
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
  show-actuator: false
  show-login-endpoint: true

# JWT配置
jwt:
  secret: 8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92
  expiration: 3600000 # 1小时
  refresh-expiration: 86400000 # 24小时

# 自定义配置
sql:
  query:
    csv:
      export:
        dir: /tmp/sql-exports

# 秒查数据源连接池配置
miaocha:
  datasource:
    hikari:
      # Doris 数据源连接池配置 - 支持查询和编辑器操作
      maximum-pool-size: 100
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 300000 # 5分钟（从10分钟调整为5分钟）
      max-lifetime: 600000 # 10分钟（从30分钟调整为10分钟）
      connection-test-query: SELECT 1
      validation-timeout: 5000
      leak-detection-threshold: 60000
      auto-commit: true
      read-only: false
      isolate-internal-queries: false

  alerts:
    mail:
      enabled: ${ALERT_MAIL_ENABLED:false}
      from: ${ALERT_MAIL_FROM:}

# Logstash配置
logstash:
  # Logstash压缩包路径
  package-path: ${LOGSTASH_PACKAGE_PATH}
  # 远程部署目录
  deploy-dir: ${LOGSTASH_DEPLOY_DIR:/opt/logstash}
  # 进程监控配置
  monitor:
    # 监控间隔时间（毫秒），默认5分钟
    interval: 300000
