name: Package

on:
  push:
    branches: [ main ]

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 需要完整历史
          submodules: true  # 自动签出所有子模块

      - name: Update submodules to latest
        run: |
          git submodule update --remote --recursive
          echo "Updated submodules:"
          git submodule status

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Configure system for Doris
        run: |
          # 关闭swap分区
          sudo swapoff -a

          # 设置系统参数
          sudo sysctl -w vm.max_map_count=2000000
          sudo sysctl -w vm.swappiness=0
          sudo sysctl -w fs.file-max=655360

          # 验证设置
          echo "=== System Configuration ==="
          echo "Swap status:"
          swapon --show
          echo "vm.max_map_count: $(cat /proc/sys/vm/max_map_count)"
          echo "vm.swappiness: $(cat /proc/sys/vm/swappiness)"
          echo "fs.file-max: $(cat /proc/sys/fs/file-max)"

      - name: Build and package
        run: mvn clean verify

      - name: List build artifacts
        run: |
          echo "=== Build Artifacts ==="
          find dist -type f -name "*.zip" -o -name "*.tar.gz" -o -name "*.jar" | head -20

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: miaocha-distribution-${{ github.sha }}
          path: |
            dist/miaocha-*-bin.zip
            dist/miaocha-*-bin.tar.gz
            dist/miaocha-*-source.zip
            dist/miaocha-*-source.tar.gz
          retention-days: 30