apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: miaocha-pr-${PR_NUMBER}
  labels:
    app: mysql
    pr-number: "${PR_NUMBER}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "log_manage_system"
        - name: TZ
          value: "Asia/Shanghai"
        ports:
        - containerPort: 3306
          name: mysql
        args:
        - "--character-set-server=utf8mb4"
        - "--collation-server=utf8mb4_unicode_ci"
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: mysql-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: miaocha-pr-${PR_NUMBER}
  labels:
    app: mysql
    pr-number: "${PR_NUMBER}"
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
    protocol: TCP
  selector:
    app: mysql 